### ISSUE TITLE
archlinux makepkg fails with new meson_post_install script

### ISSUE THREAD

**Issue by jaystrictor** [Ippytraxx/gnome-twitch#40]
Since the new `meson_post_install.sh` script is there, building with `makepkg` under archlinux fails.

I think this is due to the absolute pathnames in the script: meson is run as a non-privileged user and is not allowed to write in `/usr/...`.

```
Running custom install script /tmp/pacaurtmp-jay/gnome-twitch-git/src/gnome-twitch-git/meson_post_install.sh
Failed to create file '/usr/share/glib-2.0/schemas/gschemas.compiled.A3VZ6X': Permission denied
gtk-update-icon-cache: Failed to open file /usr/share/icons/hicolor/.icon-theme.cache : Permission denied
Traceback (most recent call last):
  File "/usr/share/meson/meson_install.py", line 226, in <module>
    do_install(datafilename)
  File "/usr/share/meson/meson_install.py", line 51, in do_install
    run_install_script(d)
  File "/usr/share/meson/meson_install.py", line 143, in run_install_script
    subprocess.check_call(final_command, env=child_env)
  File "/usr/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/pacaurtmp-jay/gnome-twitch-git/src/gnome-twitch-git/meson_post_install.sh']' returned non-zero exit status 1
FAILED: '/usr/bin/python3' '/usr/share/meson/meson_install.py' '/tmp/pacaurtmp-jay/gnome-twitch-git/src/gnome-twitch-git/build/meson-private/install.dat'
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in package().
    Aborting...
:: gnome-twitch-git cleaning skipped
:: failed to build gnome-twitch-git package(s)
```

**Comment by Ippytraxx** [comment]
I saw somebody mentioned this on the Meson Github because autotools doesn't run post-install when DESTDIR is set.

I created a simple option `do-post-install` that can be set to false when you don't want to run it.

**Comment by jaystrictor** [comment]
It works. Thanks!
